# Generated by Django 5.2.17 on 2026-08-14 09:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Center",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=24, unique=True)),
                ("name", models.CharField(max_length=180, unique=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("employee_number", models.CharField(max_length=40, unique=True)),
                ("job_title", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "centers",
                    models.ManyToManyField(
                        blank=True, related_name="staff", to="centers.center"
                    ),
                ),
                (
                    "primary_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_staff",
                        to="centers.center",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__last_name", "user__first_name", "employee_number"],
            },
        ),
        migrations.CreateModel(
            name="SpecialistProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True)),
                (
                    "staff_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="specialist_profile",
                        to="centers.staffprofile",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "staff_profile__user__last_name",
                    "staff_profile__user__first_name",
                ],
            },
        ),
        migrations.CreateModel(
            name="SpecialistCenterAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="specialist_assignments",
                        to="centers.center",
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="center_assignments",
                        to="centers.specialistprofile",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "center__name",
                    "specialist__staff_profile__user__last_name",
                ],
                "indexes": [
                    models.Index(
                        fields=["center", "specialist"],
                        name="centers_spe_center__8d4346_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("specialist", "center"),
                        name="unique_specialist_center_assignment",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_primary", True)),
                        fields=("specialist",),
                        name="one_primary_center_per_specialist",
                    ),
                ],
            },
        ),
    ]
