# Generated by Django 5.2.17 on 2026-08-14 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='phone',
            field=models.CharField(blank=True, max_length=40, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?[0-9][0-9() .-]{4,39}$')]),
        ),
    ]
