# Generated by Django 5.2.17 on 2026-08-14 09:59

import apps.casework.models
import apps.casework.storage
import apps.casework.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("centers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Beneficiary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("beneficiary_code", models.CharField(max_length=32, unique=True)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("disability_support", "Disability Support"),
                            ("child_protection", "Child Protection"),
                            ("social_protection", "Social Protection"),
                            ("rehabilitation", "Rehabilitation"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "service_status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("active", "Active"),
                            ("on_hold", "On Hold"),
                            ("exited", "Exited"),
                        ],
                        db_index=True,
                        default="applied",
                        max_length=16,
                    ),
                ),
                ("full_name", models.CharField(max_length=180)),
                ("personal_id", models.CharField(blank=True, max_length=64)),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("region", models.CharField(blank=True, max_length=120)),
                ("municipality", models.CharField(blank=True, max_length=120)),
                ("address", models.TextField(blank=True)),
                ("guardian_parent", models.CharField(blank=True, max_length=180)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("diagnosis_status", models.TextField(blank=True)),
                (
                    "barthel_index",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("first_assessment_date", models.DateField(blank=True, null=True)),
                (
                    "family_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single", "Single"),
                            ("married", "Married"),
                            ("divorced", "Divorced"),
                            ("widowed", "Widowed"),
                            ("separated", "Separated"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("first_service_date", models.DateField(blank=True, null=True)),
                (
                    "application_contract_number",
                    models.CharField(blank=True, max_length=80),
                ),
                ("exit_date", models.DateField(blank=True, db_index=True, null=True)),
                ("exit_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="beneficiaries",
                        to="centers.center",
                    ),
                ),
            ],
            options={
                "ordering": ["full_name", "beneficiary_code"],
            },
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assessment_date", models.DateField(db_index=True)),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("initial", "Initial"),
                            ("repeated", "Repeated"),
                            ("final", "Final"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "assessment_cycle_number",
                    models.PositiveIntegerField(default=1, editable=False),
                ),
                (
                    "scoring_tool",
                    models.CharField(
                        choices=[
                            ("barthel", "Barthel"),
                            ("aeps_old", "AEPS (Old)"),
                            ("aeps_new", "AEPS (New)"),
                            ("icf", "ICF-Based"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("service_schedule_count", models.PositiveIntegerField(default=0)),
                ("progress_summary", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                ("next_review_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessments",
                        to="centers.center",
                    ),
                ),
                (
                    "previous_assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="next_assessments",
                        to="casework.assessment",
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessments",
                        to="centers.specialistprofile",
                    ),
                ),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessments",
                        to="casework.beneficiary",
                    ),
                ),
            ],
            options={
                "ordering": ["-assessment_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BeneficiarySpecialistAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment_role",
                    models.CharField(
                        choices=[("primary", "Primary"), ("secondary", "Secondary")],
                        default="primary",
                        max_length=16,
                    ),
                ),
                ("from_date", models.DateField(blank=True, null=True)),
                ("to_date", models.DateField(blank=True, null=True)),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specialist_assignments",
                        to="casework.beneficiary",
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="beneficiary_assignments",
                        to="centers.specialistprofile",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "assignment_role",
                    "specialist__staff_profile__user__last_name",
                ],
            },
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="specialists",
            field=models.ManyToManyField(
                related_name="beneficiaries",
                through="casework.BeneficiarySpecialistAssignment",
                to="centers.specialistprofile",
            ),
        ),
        migrations.CreateModel(
            name="IndividualPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("plan_start_date", models.DateField(db_index=True)),
                (
                    "plan_end_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "review_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                        ],
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plans",
                        to="casework.beneficiary",
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="individual_plans",
                        to="centers.center",
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="individual_plans",
                        to="centers.specialistprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-plan_start_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IndividualPlanGoal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("goal", models.TextField()),
                ("target_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("achieved", "Achieved"),
                            ("deferred", "Deferred"),
                        ],
                        default="planned",
                        max_length=16,
                    ),
                ),
                ("progress_notes", models.TextField(blank=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="casework.individualplan",
                    ),
                ),
            ],
            options={
                "ordering": ["target_date", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrivateAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_type",
                    models.CharField(
                        choices=[
                            ("beneficiary", "Beneficiary"),
                            ("service_visit", "Service Visit"),
                            ("assessment", "Assessment"),
                            ("individual_plan", "Individual Plan"),
                            ("staff_profile", "Staff Profile"),
                        ],
                        max_length=24,
                    ),
                ),
                ("parent_id", models.UUIDField()),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        storage=apps.casework.storage.PrivateFileStorage(),
                        upload_to=apps.casework.models.private_upload_to,
                        validators=[apps.casework.validators.validate_private_upload],
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=120)),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, editable=False, max_length=64)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="private_attachments",
                        to="centers.center",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="private_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceVisit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("visit_date", models.DateField(db_index=True)),
                ("visit_month", models.DateField(db_index=True, editable=False)),
                (
                    "visit_type",
                    models.CharField(
                        choices=[
                            ("center_visit", "Center Visit"),
                            ("home_visit", "Home Visit"),
                            ("school_visit", "School Visit"),
                            ("hospital_visit", "Hospital Visit"),
                            ("community_outreach", "Community Outreach"),
                            ("remote_session", "Remote Session"),
                            ("group_session", "Group Session"),
                            ("case_conference", "Case Conference"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("no_show", "No Show"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "service_units",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("duration_minutes", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visits",
                        to="casework.beneficiary",
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_visits",
                        to="centers.center",
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_visits",
                        to="centers.specialistprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-visit_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SpecialistMonthlyServiceSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("summary_month", models.DateField(db_index=True)),
                ("completed_visits", models.PositiveIntegerField(default=0)),
                (
                    "total_service_units",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total_duration_minutes", models.PositiveIntegerField(default=0)),
                ("unique_beneficiaries", models.PositiveIntegerField(default=0)),
                ("no_show_count", models.PositiveIntegerField(default=0)),
                ("cancelled_count", models.PositiveIntegerField(default=0)),
                (
                    "last_rebuilt_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monthly_summaries",
                        to="centers.center",
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monthly_summaries",
                        to="centers.specialistprofile",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "-summary_month",
                    "specialist__staff_profile__user__last_name",
                ],
            },
        ),
        migrations.CreateModel(
            name="AssessmentDomainScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("domain", models.CharField(max_length=180)),
                (
                    "baseline_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "current_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("progress_notes", models.TextField(blank=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domain_scores",
                        to="casework.assessment",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("assessment", "domain"), name="unique_assessment_domain"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(
                fields=["center", "assessment_date", "assessment_type"],
                name="casework_as_center__a45a43_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(
                fields=["specialist", "assessment_date"],
                name="casework_as_special_b83ac6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(
                fields=["beneficiary", "assessment_date"],
                name="casework_as_benefic_00d724_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="beneficiaryspecialistassignment",
            index=models.Index(
                fields=["specialist", "beneficiary"],
                name="casework_be_special_f994e3_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="beneficiaryspecialistassignment",
            constraint=models.UniqueConstraint(
                fields=("beneficiary", "specialist"),
                name="unique_beneficiary_specialist_assignment",
            ),
        ),
        migrations.AddConstraint(
            model_name="beneficiaryspecialistassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("to_date__isnull", True),
                    ("from_date__isnull", True),
                    ("to_date__gte", models.F("from_date")),
                    _connector="OR",
                ),
                name="beneficiary_assignment_dates_ordered",
            ),
        ),
        migrations.AddIndex(
            model_name="beneficiary",
            index=models.Index(
                fields=["center", "service_status"],
                name="casework_be_center__cc1d7b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="beneficiary",
            index=models.Index(
                fields=["center", "full_name"], name="casework_be_center__e9776b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="beneficiary",
            constraint=models.UniqueConstraint(
                condition=models.Q(("personal_id", ""), _negated=True),
                fields=("personal_id",),
                name="unique_nonblank_beneficiary_personal_id",
            ),
        ),
        migrations.AddIndex(
            model_name="individualplan",
            index=models.Index(
                fields=["center", "status", "plan_start_date"],
                name="casework_in_center__ebcc18_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="individualplan",
            index=models.Index(
                fields=["specialist", "status"], name="casework_in_special_f0053f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="individualplan",
            index=models.Index(
                fields=["beneficiary", "plan_start_date"],
                name="casework_in_benefic_6616c9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="privateattachment",
            index=models.Index(
                fields=["parent_type", "parent_id"],
                name="casework_pr_parent__a6c2c2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="privateattachment",
            index=models.Index(
                fields=["center", "created_at"], name="casework_pr_center__238124_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicevisit",
            index=models.Index(
                fields=["center", "visit_date", "status"],
                name="casework_se_center__3d7bed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="servicevisit",
            index=models.Index(
                fields=["specialist", "visit_month", "status"],
                name="casework_se_special_ebbe62_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="servicevisit",
            index=models.Index(
                fields=["beneficiary", "visit_date"],
                name="casework_se_benefic_54d7d1_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicevisit",
            constraint=models.CheckConstraint(
                condition=models.Q(("service_units__gte", 0)),
                name="visit_units_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicevisit",
            constraint=models.CheckConstraint(
                condition=models.Q(("duration_minutes__gte", 0)),
                name="visit_duration_nonnegative",
            ),
        ),
        migrations.AddIndex(
            model_name="specialistmonthlyservicesummary",
            index=models.Index(
                fields=["center", "summary_month"],
                name="casework_sp_center__6354cb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="specialistmonthlyservicesummary",
            index=models.Index(
                fields=["specialist", "summary_month"],
                name="casework_sp_special_3fce61_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="specialistmonthlyservicesummary",
            constraint=models.UniqueConstraint(
                fields=("specialist", "center", "summary_month"),
                name="unique_specialist_center_month_summary",
            ),
        ),
    ]
