# Generated by Django 5.2.17 on 2026-08-14 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casework', '0001_initial'),
        ('centers', '0002_alter_center_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='phone',
            field=models.CharField(blank=True, max_length=40, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?[0-9][0-9() .-]{4,39}$')]),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assessment_type', 'initial'), ('previous_assessment__isnull', True)), models.Q(('assessment_type__in', ('repeated', 'final')), ('previous_assessment__isnull', False)), _connector='OR'), name='assessment_type_previous_consistent'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(('next_review_date__isnull', True), ('next_review_date__gte', models.F('assessment_date')), _connector='OR'), name='assessment_review_date_ordered'),
        ),
        migrations.AddConstraint(
            model_name='individualplan',
            constraint=models.CheckConstraint(condition=models.Q(('plan_end_date__isnull', True), ('plan_end_date__gte', models.F('plan_start_date')), _connector='OR'), name='individual_plan_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='servicevisit',
            constraint=models.CheckConstraint(condition=models.Q(('visit_month__day', 1)), name='visit_month_is_first_day'),
        ),
        migrations.AddConstraint(
            model_name='servicevisit',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'cancelled'), _negated=True), ('service_units', 0), _connector='OR'), name='cancelled_visit_has_zero_units'),
        ),
        migrations.AddConstraint(
            model_name='specialistmonthlyservicesummary',
            constraint=models.CheckConstraint(condition=models.Q(('summary_month__day', 1)), name='summary_month_is_first_day'),
        ),
    ]
