# Generated by Django 5.2.17 on 2026-08-20 10:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("casework", "0003_privateattachment_document_type"),
        ("centers", "0003_staff_contract_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Municipality",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=48, unique=True)),
                ("name_en", models.CharField(max_length=180)),
                ("name_ka", models.CharField(max_length=180)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("source_version", models.CharField(blank=True, max_length=120)),
            ],
            options={
                "ordering": ["region__name_en", "name_en"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=48, unique=True)),
                ("name_en", models.CharField(max_length=180)),
                ("name_ka", models.CharField(max_length=180)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("source_version", models.CharField(blank=True, max_length=120)),
            ],
            options={
                "ordering": ["name_en"],
            },
        ),
        migrations.CreateModel(
            name="ServiceDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=48, unique=True)),
                ("name_en", models.CharField(max_length=180)),
                ("name_ka", models.CharField(max_length=180)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("source_version", models.CharField(blank=True, max_length=120)),
                (
                    "family",
                    models.CharField(
                        choices=[
                            ("home_care", "Home Care"),
                            ("food_delivery", "Food Delivery"),
                            ("early_intervention", "Early Intervention"),
                            ("future", "Future Service"),
                            ("legacy", "Legacy Service"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("reporting_order", models.PositiveIntegerField(default=0)),
                ("allow_same_service_overlap", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["reporting_order", "name_en", "code"],
            },
        ),
        migrations.CreateModel(
            name="SocialStatusDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=48, unique=True)),
                ("name_en", models.CharField(max_length=180)),
                ("name_ka", models.CharField(max_length=180)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("source_version", models.CharField(blank=True, max_length=120)),
                (
                    "sensitivity",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("restricted", "Restricted"),
                        ],
                        default="restricted",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "ordering": ["name_en", "code"],
            },
        ),
        migrations.CreateModel(
            name="CenterServiceOffering",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_offerings",
                        to="centers.center",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="center_offerings",
                        to="casework.servicedefinition",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "center__name",
                    "service__reporting_order",
                    "service__name_en",
                ],
            },
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="municipality_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="beneficiaries",
                to="casework.municipality",
                verbose_name="Municipality",
            ),
        ),
        migrations.AddField(
            model_name="municipality",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="municipalities",
                to="casework.region",
            ),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="region_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="beneficiaries",
                to="casework.region",
                verbose_name="Region",
            ),
        ),
        migrations.CreateModel(
            name="DiagnosisDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=48, unique=True)),
                ("name_en", models.CharField(max_length=180)),
                ("name_ka", models.CharField(max_length=180)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("source_version", models.CharField(blank=True, max_length=120)),
                ("coding_system", models.CharField(max_length=80)),
                (
                    "applicable_services",
                    models.ManyToManyField(
                        blank=True,
                        related_name="diagnosis_definitions",
                        to="casework.servicedefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["coding_system", "code"],
            },
        ),
        migrations.CreateModel(
            name="ServiceEnrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("episode_code", models.CharField(max_length=48, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("completed", "Completed"),
                            ("exited", "Exited"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("start_date", models.DateField(blank=True, db_index=True, null=True)),
                ("end_date", models.DateField(blank=True, db_index=True, null=True)),
                ("first_service_date", models.DateField(blank=True, null=True)),
                (
                    "application_contract_number",
                    models.CharField(blank=True, max_length=80),
                ),
                ("exit_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "legacy_source_id",
                    models.UUIDField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
                (
                    "legacy_service_value",
                    models.CharField(blank=True, editable=False, max_length=32),
                ),
                (
                    "legacy_status_value",
                    models.CharField(blank=True, editable=False, max_length=16),
                ),
                (
                    "legacy_dates_incomplete",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="casework.beneficiary",
                    ),
                ),
                (
                    "prior_enrollment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subsequent_enrollments",
                        to="casework.serviceenrollment",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="casework.servicedefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EnrollmentStateEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("legacy_import", "Legacy Import"),
                            ("created", "Created"),
                            ("admission", "Admission"),
                            ("suspension", "Suspension"),
                            ("resumption", "Resumption"),
                            ("transfer", "Transfer"),
                            ("completion", "Completion"),
                            ("exit", "Exit"),
                            ("cancellation", "Cancellation"),
                            ("re_enrollment", "Re-enrollment"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "previous_state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("completed", "Completed"),
                            ("exited", "Exited"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "new_state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("completed", "Completed"),
                            ("exited", "Exited"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("reason", models.CharField(blank=True, max_length=180)),
                ("notes", models.TextField(blank=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrollment_state_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="state_events",
                        to="casework.serviceenrollment",
                    ),
                ),
            ],
            options={
                "ordering": ["effective_date", "created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="EnrollmentSpecialistAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment_role",
                    models.CharField(
                        choices=[("primary", "Primary"), ("secondary", "Secondary")],
                        default="primary",
                        max_length=16,
                    ),
                ),
                ("valid_from", models.DateField(blank=True, db_index=True, null=True)),
                ("valid_to", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "legacy_dates_incomplete",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollment_assignments",
                        to="centers.specialistprofile",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="specialist_assignments",
                        to="casework.serviceenrollment",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "assignment_role",
                    "specialist__staff_profile__user__last_name",
                ],
            },
        ),
        migrations.CreateModel(
            name="EnrollmentCenterPlacement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("valid_from", models.DateField(blank=True, db_index=True, null=True)),
                ("valid_to", models.DateField(blank=True, db_index=True, null=True)),
                ("transfer_reason", models.CharField(blank=True, max_length=180)),
                ("notes", models.TextField(blank=True)),
                (
                    "legacy_dates_incomplete",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollment_placements",
                        to="centers.center",
                    ),
                ),
                (
                    "offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollment_placements",
                        to="casework.centerserviceoffering",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="center_placements",
                        to="casework.serviceenrollment",
                    ),
                ),
            ],
            options={
                "ordering": ["valid_from", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="BeneficiaryDiagnosis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recorded_on",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("valid_from", models.DateField(blank=True, db_index=True, null=True)),
                ("valid_to", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("reported", "Reported"),
                            ("unverified", "Unverified"),
                            ("verified", "Verified"),
                        ],
                        default="unverified",
                        max_length=16,
                    ),
                ),
                ("visible_to_specialists", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diagnoses",
                        to="casework.beneficiary",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_beneficiary_diagnoses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="beneficiary_values",
                        to="casework.diagnosisdefinition",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diagnoses",
                        to="casework.serviceenrollment",
                    ),
                ),
            ],
            options={
                "ordering": ["-valid_from", "definition__code"],
            },
        ),
        migrations.AddField(
            model_name="assessment",
            name="enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assessments",
                to="casework.serviceenrollment",
            ),
        ),
        migrations.AddField(
            model_name="individualplan",
            name="enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="plans",
                to="casework.serviceenrollment",
            ),
        ),
        migrations.AddField(
            model_name="servicevisit",
            name="enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="visits",
                to="casework.serviceenrollment",
            ),
        ),
        migrations.CreateModel(
            name="BeneficiarySocialStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recorded_on",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("valid_from", models.DateField(blank=True, db_index=True, null=True)),
                ("valid_to", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("reported", "Reported"),
                            ("unverified", "Unverified"),
                            ("verified", "Verified"),
                        ],
                        default="unverified",
                        max_length=16,
                    ),
                ),
                ("visible_to_specialists", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="social_statuses",
                        to="casework.beneficiary",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_beneficiary_social_statuses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="social_statuses",
                        to="casework.serviceenrollment",
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="beneficiary_values",
                        to="casework.socialstatusdefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["-valid_from", "definition__code"],
            },
        ),
        migrations.AddIndex(
            model_name="municipality",
            index=models.Index(
                fields=["region", "is_active"], name="casework_mu_region__63a620_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="centerserviceoffering",
            index=models.Index(
                fields=["center", "service", "is_active"],
                name="casework_ce_center__3e0701_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="centerserviceoffering",
            constraint=models.UniqueConstraint(
                fields=("center", "service", "valid_from"),
                name="unique_center_service_offering_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="centerserviceoffering",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_to__isnull", True),
                    ("valid_from__isnull", True),
                    ("valid_to__gt", models.F("valid_from")),
                    _connector="OR",
                ),
                name="center_service_offering_dates_ordered",
            ),
        ),
        migrations.AddIndex(
            model_name="serviceenrollment",
            index=models.Index(
                fields=["beneficiary", "status"], name="casework_se_benefic_8fc495_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="serviceenrollment",
            index=models.Index(
                fields=["service", "status"], name="casework_se_service_2da91e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="serviceenrollment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_date__isnull", True),
                    ("start_date__isnull", True),
                    ("end_date__gt", models.F("start_date")),
                    _connector="OR",
                ),
                name="service_enrollment_dates_ordered",
            ),
        ),
        migrations.AddIndex(
            model_name="enrollmentstateevent",
            index=models.Index(
                fields=["enrollment", "effective_date"],
                name="casework_en_enrollm_c8fe79_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="enrollmentspecialistassignment",
            index=models.Index(
                fields=["enrollment", "valid_from", "valid_to"],
                name="casework_en_enrollm_ac4d1d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="enrollmentspecialistassignment",
            index=models.Index(
                fields=["specialist", "valid_from", "valid_to"],
                name="casework_en_special_8c85f5_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollmentspecialistassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_to__isnull", True),
                    ("valid_from__isnull", True),
                    ("valid_to__gt", models.F("valid_from")),
                    _connector="OR",
                ),
                name="enrollment_assignment_dates_ordered",
            ),
        ),
        migrations.AddIndex(
            model_name="enrollmentcenterplacement",
            index=models.Index(
                fields=["enrollment", "valid_from", "valid_to"],
                name="casework_en_enrollm_754344_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="enrollmentcenterplacement",
            index=models.Index(
                fields=["center", "valid_from", "valid_to"],
                name="casework_en_center__72cd0c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollmentcenterplacement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_to__isnull", True),
                    ("valid_from__isnull", True),
                    ("valid_to__gt", models.F("valid_from")),
                    _connector="OR",
                ),
                name="enrollment_placement_dates_ordered",
            ),
        ),
        migrations.AddIndex(
            model_name="beneficiarydiagnosis",
            index=models.Index(
                fields=["beneficiary", "valid_from", "valid_to"],
                name="casework_be_benefic_38a2a8_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="beneficiarydiagnosis",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_to__isnull", True),
                    ("valid_from__isnull", True),
                    ("valid_to__gt", models.F("valid_from")),
                    _connector="OR",
                ),
                name="beneficiary_diagnosis_dates_ordered",
            ),
        ),
        migrations.AddIndex(
            model_name="beneficiarysocialstatus",
            index=models.Index(
                fields=["beneficiary", "valid_from", "valid_to"],
                name="casework_be_benefic_cd9aeb_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="beneficiarysocialstatus",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_to__isnull", True),
                    ("valid_from__isnull", True),
                    ("valid_to__gt", models.F("valid_from")),
                    _connector="OR",
                ),
                name="beneficiary_social_status_dates_ordered",
            ),
        ),
    ]
