# Generated by Django 5.2.17 on 2026-08-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("casework", "0004_beneficiary_enrollment_foundation"),
        ("centers", "0003_staff_contract_fields"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="enrollmentcenterplacement",
            name="enrollment_placement_dates_ordered",
        ),
        migrations.RemoveConstraint(
            model_name="enrollmentspecialistassignment",
            name="enrollment_assignment_dates_ordered",
        ),
        migrations.RemoveConstraint(
            model_name="serviceenrollment",
            name="service_enrollment_dates_ordered",
        ),
        migrations.AddConstraint(
            model_name="enrollmentcenterplacement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_to__isnull", True),
                    ("valid_from__isnull", True),
                    ("valid_to__gte", models.F("valid_from")),
                    _connector="OR",
                ),
                name="enrollment_placement_dates_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollmentspecialistassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_to__isnull", True),
                    ("valid_from__isnull", True),
                    ("valid_to__gte", models.F("valid_from")),
                    _connector="OR",
                ),
                name="enrollment_assignment_dates_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="serviceenrollment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_date__isnull", True),
                    ("start_date__isnull", True),
                    ("end_date__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="service_enrollment_dates_ordered",
            ),
        ),
    ]
