# Generated by Django 5.2.17 on 2026-08-20 11:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


ACTIVITIES = (
    ("INDIVIDUAL-MEETING", "Individual meeting", "ინდივიდუალური შეხვედრა", 10),
    ("GROUP-MEETING", "Group meeting", "ჯგუფური შეხვედრა", 20),
    (
        "PARENT-GUARDIAN-CONSULTATION",
        "Parent or guardian consultation",
        "მშობლის ან მეურვის კონსულტაცია",
        30,
    ),
    ("HYGIENE-CARE", "Hygiene care", "ჰიგიენური მოვლა", 40),
    ("PSYCHOSOCIAL-SUPPORT", "Psychosocial support", "ფსიქოსოციალური მხარდაჭერა", 50),
    ("HOUSEHOLD-HELP", "Household help", "საოჯახო დახმარება", 60),
    ("MEDICATION-MONITORING", "Medication monitoring", "მედიკამენტების მონიტორინგი", 70),
    ("HEALTH-CHECKS", "Health checks", "ჯანმრთელობის შემოწმება", 80),
    ("BENEFICIARY-TRANSPORT", "Beneficiary transport", "ბენეფიციარის ტრანსპორტირება", 90),
    ("SHOPPING-SUPPORT", "Shopping support", "საყიდლებზე დახმარება", 100),
    ("FOOD-DELIVERY", "Food delivery", "საკვების მიწოდება", 110),
    ("OTHER", "Other", "სხვა", 900),
)

LOCATIONS = (
    ("CENTER", "Center", "ცენტრი", "physical", 10),
    ("HOME", "Home", "სახლი", "physical", 20),
    ("SCHOOL", "School", "სკოლა", "physical", 30),
    ("HOSPITAL", "Hospital", "საავადმყოფო", "physical", 40),
    ("COMMUNITY", "Community", "თემი", "physical", 50),
    ("REMOTE", "Remote", "დისტანციური", "remote", 60),
    ("OTHER", "Other", "სხვა", "physical", 900),
)


def seed_visit_catalogs_and_backfill(apps, schema_editor):
    Activity = apps.get_model("casework", "ServiceActivityDefinition")
    Location = apps.get_model("casework", "VisitLocationDefinition")
    Visit = apps.get_model("casework", "ServiceVisit")

    for code, name_en, name_ka, order in ACTIVITIES:
        Activity.objects.update_or_create(
            code=code,
            defaults={
                "name_en": name_en,
                "name_ka": name_ka,
                "reporting_order": order,
                "is_active": True,
                "source_version": "SSK-SERVICE-VISITS-2026-08",
            },
        )
    for code, name_en, name_ka, kind, order in LOCATIONS:
        Location.objects.update_or_create(
            code=code,
            defaults={
                "name_en": name_en,
                "name_ka": name_ka,
                "kind": kind,
                "reporting_order": order,
                "is_active": True,
                "source_version": "SSK-SERVICE-VISITS-2026-08",
            },
        )

    activity_by_code = {row.code: row for row in Activity.objects.all()}
    location_by_code = {row.code: row for row in Location.objects.all()}
    location_mapping = {
        "center_visit": "CENTER",
        "home_visit": "HOME",
        "school_visit": "SCHOOL",
        "hospital_visit": "HOSPITAL",
        "community_outreach": "COMMUNITY",
        "remote_session": "REMOTE",
        "group_session": "CENTER",
        "case_conference": "CENTER",
        "other": "OTHER",
    }
    for visit in Visit.objects.all().iterator():
        visit.activity_id = activity_by_code[
            "GROUP-MEETING"
            if visit.legacy_visit_type == "group_session"
            else "INDIVIDUAL-MEETING"
        ].pk
        visit.delivery_location_id = location_by_code[
            location_mapping.get(visit.legacy_visit_type, "OTHER")
        ].pk
        visit.participation_format = (
            "group" if visit.legacy_visit_type == "group_session" else "individual"
        )
        visit.participants = 2 if visit.participation_format == "group" else 1
        if visit.status in {"no_show", "cancelled"}:
            visit.service_units = 0
        visit.save(
            update_fields=[
                "activity",
                "delivery_location",
                "participation_format",
                "participants",
                "service_units",
            ]
        )


def preserve_catalogs_on_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("casework", "0007_require_transaction_enrollments"),
        ("centers", "0003_staff_contract_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitLocationDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=48, unique=True)),
                ("name_en", models.CharField(max_length=180)),
                ("name_ka", models.CharField(max_length=180)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("source_version", models.CharField(blank=True, max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[("physical", "Physical"), ("remote", "Remote")],
                        default="physical",
                        max_length=16,
                    ),
                ),
                ("reporting_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["reporting_order", "name_en", "code"],
            },
        ),
        migrations.RenameField(
            model_name="servicevisit",
            old_name="visit_type",
            new_name="legacy_visit_type",
        ),
        migrations.AddField(
            model_name="servicevisit",
            name="cancellation_reason",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name="servicevisit",
            name="legacy_visit_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("center_visit", "Center Visit"),
                    ("home_visit", "Home Visit"),
                    ("school_visit", "School Visit"),
                    ("hospital_visit", "Hospital Visit"),
                    ("community_outreach", "Community Outreach"),
                    ("remote_session", "Remote Session"),
                    ("group_session", "Group Session"),
                    ("case_conference", "Case Conference"),
                    ("other", "Other"),
                ],
                db_index=True,
                editable=False,
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="servicevisit",
            name="participants",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="servicevisit",
            name="participation_format",
            field=models.CharField(
                choices=[("individual", "Individual"), ("group", "Group")],
                db_index=True,
                default="individual",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="servicevisit",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("completed", "Completed"),
                    ("no_show", "No Show"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="specialistmonthlyservicesummary",
            name="planned_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="ServiceActivityDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=48, unique=True)),
                ("name_en", models.CharField(max_length=180)),
                ("name_ka", models.CharField(max_length=180)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("source_version", models.CharField(blank=True, max_length=120)),
                (
                    "default_unit_label",
                    models.CharField(default="service unit", max_length=48),
                ),
                ("reporting_order", models.PositiveIntegerField(default=0)),
                (
                    "applicable_services",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Leave empty to allow this activity for every service.",
                        related_name="service_activities",
                        to="casework.servicedefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["reporting_order", "name_en", "code"],
            },
        ),
        migrations.AddField(
            model_name="servicevisit",
            name="activity",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="service_visits",
                to="casework.serviceactivitydefinition",
            ),
        ),
        migrations.CreateModel(
            name="ServiceVisitCorrection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.CharField(max_length=240)),
                ("before_values", models.JSONField()),
                ("after_values", models.JSONField()),
                (
                    "corrected_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_visit_corrections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corrections",
                        to="casework.servicevisit",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EnrollmentServiceSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("schedule_month", models.DateField(db_index=True)),
                (
                    "participation_format",
                    models.CharField(
                        choices=[("individual", "Individual"), ("group", "Group")],
                        default="individual",
                        max_length=16,
                    ),
                ),
                (
                    "planned_visits",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "planned_units",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "expected_participants",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_schedules",
                        to="casework.serviceenrollment",
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_schedules",
                        to="casework.serviceactivitydefinition",
                    ),
                ),
                (
                    "delivery_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_schedules",
                        to="casework.visitlocationdefinition",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "-schedule_month",
                    "enrollment__episode_code",
                    "activity__reporting_order",
                ],
            },
        ),
        migrations.AddField(
            model_name="servicevisit",
            name="delivery_location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="service_visits",
                to="casework.visitlocationdefinition",
            ),
        ),
        migrations.RunPython(
            seed_visit_catalogs_and_backfill,
            preserve_catalogs_on_reverse,
        ),
        migrations.AlterField(
            model_name="servicevisit",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="service_visits",
                to="casework.serviceactivitydefinition",
            ),
        ),
        migrations.AlterField(
            model_name="servicevisit",
            name="delivery_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="service_visits",
                to="casework.visitlocationdefinition",
            ),
        ),
        migrations.AddIndex(
            model_name="servicevisit",
            index=models.Index(
                fields=["activity", "delivery_location", "visit_month", "status"],
                name="casework_se_activit_ef0c1d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicevisit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status__in", ["planned", "no_show"]), _negated=True),
                    ("service_units", 0),
                    _connector="OR",
                ),
                name="undelivered_visit_has_zero_units",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicevisit",
            constraint=models.CheckConstraint(
                condition=models.Q(("participants__gt", 0)),
                name="visit_participants_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="servicevisitcorrection",
            index=models.Index(
                fields=["visit", "created_at"], name="casework_se_visit_i_d7d043_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollmentserviceschedule",
            index=models.Index(
                fields=["enrollment", "schedule_month"],
                name="casework_en_enrollm_830e21_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="enrollmentserviceschedule",
            index=models.Index(
                fields=["activity", "delivery_location", "schedule_month"],
                name="casework_en_activit_3a1c2a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollmentserviceschedule",
            constraint=models.UniqueConstraint(
                fields=(
                    "enrollment",
                    "schedule_month",
                    "activity",
                    "delivery_location",
                    "participation_format",
                ),
                name="unique_enrollment_month_service_schedule",
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollmentserviceschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(("schedule_month__day", 1)),
                name="service_schedule_month_is_first_day",
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollmentserviceschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(("planned_visits__gt", 0)),
                name="service_schedule_visits_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollmentserviceschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(("planned_units__gte", 0)),
                name="service_schedule_units_nonnegative",
            ),
        ),
    ]
