# Generated by Django 5.2.17 on 2026-08-24 12:10

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


INSTRUMENTS = (
    ("BARTHEL", "Barthel", "barthel", "BARTHEL"),
    ("AEPS-OLD", "AEPS (Old)", "aeps_old", "AEPS-OLD"),
    ("AEPS-NEW", "AEPS (New)", "aeps_new", "AEPS-NEW"),
    ("ICF", "ICF-Based", "icf", "ICF"),
    ("OTHER", "Other assessment tool", "other", "OTHER"),
)

EARLY_INTERVENTION_DOMAINS = (
    ("GROSS_MOTOR", "Gross motor"),
    ("FINE_MOTOR", "Fine motor"),
    ("ADAPTIVE", "Adaptive"),
    ("COGNITIVE", "Cognitive"),
    ("SOCIAL_COMMUNICATION", "Social communication"),
    ("SOCIAL_EMOTIONAL", "Social-emotional"),
    ("SCHOOL_READINESS", "School readiness"),
    ("LITERACY", "Literacy"),
    ("MATHEMATICS", "Mathematics"),
)


def seed_and_migrate_assessments(apps, schema_editor):
    Assessment = apps.get_model("casework", "Assessment")
    AssessmentDomainScore = apps.get_model("casework", "AssessmentDomainScore")
    AssessmentInstrument = apps.get_model("casework", "AssessmentInstrument")
    AssessmentResponse = apps.get_model("casework", "AssessmentResponse")
    AssessmentResponsibleSpecialist = apps.get_model(
        "casework", "AssessmentResponsibleSpecialist"
    )
    AssessmentScoreBand = apps.get_model("casework", "AssessmentScoreBand")
    AssessmentTemplateField = apps.get_model("casework", "AssessmentTemplateField")
    AssessmentTemplateSection = apps.get_model("casework", "AssessmentTemplateSection")
    AssessmentTemplateVersion = apps.get_model("casework", "AssessmentTemplateVersion")

    instrument_by_identifier = {}
    for code, name, identifier, lineage_code in INSTRUMENTS:
        instrument, _ = AssessmentInstrument.objects.get_or_create(
            code=code,
            defaults={
                "name": name,
                "identifier": identifier,
                "lineage_code": lineage_code,
                "description": "Structural instrument identifier supplied by SSK requirements.",
            },
        )
        instrument_by_identifier[identifier] = instrument

    legacy_template_by_identifier = {}
    legacy_total_field_by_identifier = {}
    for identifier, instrument in instrument_by_identifier.items():
        template = AssessmentTemplateVersion.objects.create(
            instrument=instrument,
            version="legacy-1",
            name=f"{instrument.name} legacy preserved values",
            status="withdrawn",
            scoring_method="sum",
            score_minimum=Decimal("0"),
            score_increment=Decimal("0.01"),
            is_legacy=True,
            publication_notes=(
                "Migration-only version. Original totals and free-text domain rows are preserved "
                "without inferring licensed questions or clinical mappings."
            ),
            published_at=timezone.now(),
        )
        section = AssessmentTemplateSection.objects.create(
            template_version=template,
            code="LEGACY",
            name="Legacy preserved values",
        )
        total_field = AssessmentTemplateField.objects.create(
            section=section,
            code="LEGACY_TOTAL",
            label="Legacy preserved total",
            response_type="numeric",
            minimum_value=Decimal("0"),
            value_increment=Decimal("0.01"),
            include_in_total=True,
        )
        legacy_template_by_identifier[identifier] = template
        legacy_total_field_by_identifier[identifier] = total_field

    barthel = instrument_by_identifier["barthel"]
    barthel_draft = AssessmentTemplateVersion.objects.create(
        instrument=barthel,
        version="structural-draft-1",
        name="Barthel structural draft",
        status="draft",
        scoring_method="sum",
        score_minimum=Decimal("0"),
        score_maximum=Decimal("100"),
        score_increment=Decimal("1"),
        publication_notes=(
            "Structural example only. Band labels and clinical publication require owner approval. "
            "Configured bounds are inclusive and adjacent by one score point."
        ),
    )
    barthel_section = AssessmentTemplateSection.objects.create(
        template_version=barthel_draft,
        code="TOTAL",
        name="Total score",
    )
    AssessmentTemplateField.objects.create(
        section=barthel_section,
        code="TOTAL_SCORE",
        label="Total score",
        response_type="numeric",
        minimum_value=Decimal("0"),
        maximum_value=Decimal("100"),
        value_increment=Decimal("1"),
        include_in_total=True,
    )
    for order, (code, label, lower, upper) in enumerate(
        (
            ("STRUCTURAL_1", "Structural band 1", 0, 65),
            ("STRUCTURAL_2", "Structural band 2", 66, 75),
            ("STRUCTURAL_3", "Structural band 3", 76, 95),
            ("STRUCTURAL_4", "Structural band 4", 96, 100),
        ),
        start=1,
    ):
        AssessmentScoreBand.objects.create(
            template_version=barthel_draft,
            code=code,
            label=label,
            lower_bound=Decimal(lower),
            upper_bound=Decimal(upper),
            display_order=order,
        )

    for identifier in ("aeps_old", "aeps_new"):
        instrument = instrument_by_identifier[identifier]
        template = AssessmentTemplateVersion.objects.create(
            instrument=instrument,
            version="structural-draft-1",
            name=f"{instrument.name} early-intervention domain structure",
            status="draft",
            scoring_method="none",
            publication_notes=(
                "Structural domains only. No proprietary questions are included. Assessment-state, "
                "percentage, delay thresholds, and publication require clinical owner approval."
            ),
        )
        section = AssessmentTemplateSection.objects.create(
            template_version=template,
            code="EARLY_INTERVENTION_DOMAINS",
            name="Early-intervention domains",
        )
        for order, (code, label) in enumerate(EARLY_INTERVENTION_DOMAINS, start=1):
            AssessmentTemplateField.objects.create(
                section=section,
                code=code,
                label=label,
                response_type="percentage",
                display_order=order,
                minimum_value=Decimal("0"),
                maximum_value=Decimal("100"),
                value_increment=Decimal("0.01"),
                allow_not_assessed=True,
                allow_not_applicable=True,
            )

    chain_state = {}
    root_counts = {}
    migrated_at = timezone.now()
    assessments = Assessment.objects.order_by("assessment_date", "created_at", "pk")
    for assessment in assessments.iterator():
        identifier = assessment.scoring_tool
        template = legacy_template_by_identifier.get(identifier)
        if template is None:
            template = legacy_template_by_identifier["other"]
            identifier = "other"
        previous_state = chain_state.get(assessment.previous_assessment_id)
        if previous_state and previous_state["identifier"] == identifier:
            chain_id = previous_state["chain_id"]
            chain_number = previous_state["chain_number"]
            sequence = previous_state["sequence"] + 1
        else:
            root_key = (assessment.enrollment_id, identifier)
            chain_number = root_counts.get(root_key, 0) + 1
            root_counts[root_key] = chain_number
            chain_id = assessment.pk
            sequence = 1
        Assessment.objects.filter(pk=assessment.pk).update(
            template_version_id=template.pk,
            chain_id=chain_id,
            chain_number=chain_number,
            assessment_cycle_number=sequence,
            status="completed",
            scoring_rule_version=template.version,
            calculated_at=migrated_at,
            calculation_trace={
                "migration": "legacy-assessment-preservation",
                "instrument_code": template.instrument.code,
                "template_version": template.version,
                "total_score": str(assessment.total_score),
            },
        )
        AssessmentResponse.objects.create(
            assessment_id=assessment.pk,
            template_field_id=legacy_total_field_by_identifier[identifier].pk,
            state="assessed",
            numeric_value=assessment.total_score,
        )
        AssessmentResponsibleSpecialist.objects.get_or_create(
            assessment_id=assessment.pk,
            specialist_id=assessment.specialist_id,
        )
        chain_state[assessment.pk] = {
            "identifier": identifier,
            "chain_id": chain_id,
            "chain_number": chain_number,
            "sequence": sequence,
        }

    AssessmentDomainScore.objects.update(mapping_status="review_required")


def reverse_assessment_migration(apps, schema_editor):
    Assessment = apps.get_model("casework", "Assessment")
    AssessmentResponse = apps.get_model("casework", "AssessmentResponse")
    AssessmentResponsibleSpecialist = apps.get_model(
        "casework", "AssessmentResponsibleSpecialist"
    )
    AssessmentResponse.objects.all().delete()
    AssessmentResponsibleSpecialist.objects.all().delete()
    Assessment.objects.update(template_version=None)


class Migration(migrations.Migration):

    dependencies = [
        ("casework", "0008_service_visit_delivery_expansion"),
        ("centers", "0003_staff_contract_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentInstrument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=48, unique=True)),
                ("name", models.CharField(max_length=180)),
                (
                    "identifier",
                    models.CharField(
                        choices=[
                            ("barthel", "Barthel"),
                            ("aeps_old", "AEPS (Old)"),
                            ("aeps_new", "AEPS (New)"),
                            ("icf", "ICF-Based"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=16,
                    ),
                ),
                (
                    "lineage_code",
                    models.CharField(
                        help_text="Assessments may be chained only within the same lineage code.",
                        max_length=48,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "ordering": ["name", "code"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentTemplateField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64)),
                ("label", models.CharField(max_length=240)),
                ("help_text", models.TextField(blank=True)),
                (
                    "response_type",
                    models.CharField(
                        choices=[
                            ("numeric", "Numeric score"),
                            ("percentage", "Percentage"),
                            ("assessed_state", "Assessed or not assessed"),
                            ("choice", "Choice"),
                            ("text", "Text"),
                            ("not_applicable", "Not applicable"),
                        ],
                        max_length=24,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_required", models.BooleanField(default=True)),
                (
                    "minimum_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "maximum_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "value_increment",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("allowed_choices", models.JSONField(blank=True, default=list)),
                ("allow_not_assessed", models.BooleanField(default=False)),
                ("allow_not_applicable", models.BooleanField(default=False)),
                ("include_in_total", models.BooleanField(default=False)),
                ("is_delayed_domain", models.BooleanField(default=False)),
                (
                    "delayed_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "delayed_operator",
                    models.CharField(
                        choices=[
                            ("lt", "Below threshold"),
                            ("lte", "At or below threshold"),
                            ("gt", "Above threshold"),
                            ("gte", "At or above threshold"),
                        ],
                        default="lt",
                        max_length=4,
                    ),
                ),
            ],
            options={
                "ordering": ["section__display_order", "display_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentTemplateSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=48)),
                ("name", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="assessment",
            name="calculated_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="assessment",
            name="calculation_trace",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="assessment",
            name="chain_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="assessment",
            name="chain_number",
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name="assessment",
            name="corrected_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assessment_corrections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="correction_reason",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="assessment",
            name="delayed_domain_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="assessment",
            name="derived_classification",
            field=models.CharField(blank=True, editable=False, max_length=180),
        ),
        migrations.AddField(
            model_name="assessment",
            name="revision_number",
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name="assessment",
            name="revision_of",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="corrections",
                to="casework.assessment",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="scoring_rule_version",
            field=models.CharField(blank=True, editable=False, max_length=48),
        ),
        migrations.AddField(
            model_name="assessment",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("completed", "Completed"),
                    ("superseded", "Superseded by correction"),
                ],
                db_index=True,
                default="draft",
                editable=False,
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="assessmentdomainscore",
            name="mapping_status",
            field=models.CharField(
                choices=[("review_required", "Review required"), ("mapped", "Mapped")],
                default="review_required",
                editable=False,
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="total_score",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.CreateModel(
            name="AssessmentResponsibleSpecialist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsible_specialist_links",
                        to="casework.assessment",
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessment_responsibilities",
                        to="centers.specialistprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["specialist__staff_profile__user__last_name"],
            },
        ),
        migrations.AddField(
            model_name="assessment",
            name="responsible_specialists",
            field=models.ManyToManyField(
                related_name="responsible_assessments",
                through="casework.AssessmentResponsibleSpecialist",
                to="centers.specialistprofile",
            ),
        ),
        migrations.CreateModel(
            name="AssessmentResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("assessed", "Assessed"),
                            ("not_assessed", "Not assessed"),
                            ("not_applicable", "Not applicable"),
                        ],
                        default="assessed",
                        max_length=16,
                    ),
                ),
                (
                    "numeric_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("text_value", models.TextField(blank=True)),
                ("choice_value", models.CharField(blank=True, max_length=240)),
                ("notes", models.TextField(blank=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="casework.assessment",
                    ),
                ),
                (
                    "template_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responses",
                        to="casework.assessmenttemplatefield",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "template_field__section__display_order",
                    "template_field__display_order",
                    "created_at",
                ],
            },
        ),
        migrations.AddField(
            model_name="assessmentdomainscore",
            name="template_field",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="legacy_domain_scores",
                to="casework.assessmenttemplatefield",
            ),
        ),
        migrations.AddField(
            model_name="assessmenttemplatefield",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                to="casework.assessmenttemplatesection",
            ),
        ),
        migrations.CreateModel(
            name="AssessmentTemplateVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.CharField(max_length=48)),
                ("name", models.CharField(max_length=180)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "scoring_method",
                    models.CharField(
                        choices=[
                            ("sum", "Sum"),
                            ("average", "Average"),
                            ("none", "No total"),
                        ],
                        default="sum",
                        max_length=16,
                    ),
                ),
                (
                    "score_minimum",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "score_maximum",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "score_increment",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "comparison_group",
                    models.CharField(
                        blank=True,
                        help_text="Different versions are comparable only when this explicit group is the same.",
                        max_length=48,
                    ),
                ),
                ("is_legacy", models.BooleanField(db_index=True, default=False)),
                ("publication_notes", models.TextField(blank=True)),
                (
                    "published_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "applicable_services",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Leave empty to allow this version for every service.",
                        related_name="assessment_template_versions",
                        to="casework.servicedefinition",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="template_versions",
                        to="casework.assessmentinstrument",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="published_assessment_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["instrument__name", "version"],
            },
        ),
        migrations.AddField(
            model_name="assessmenttemplatesection",
            name="template_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="casework.assessmenttemplateversion",
            ),
        ),
        migrations.CreateModel(
            name="AssessmentScoreBand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=48)),
                ("label", models.CharField(max_length=180)),
                ("lower_bound", models.DecimalField(decimal_places=2, max_digits=10)),
                ("upper_bound", models.DecimalField(decimal_places=2, max_digits=10)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "template_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_bands",
                        to="casework.assessmenttemplateversion",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "lower_bound"],
            },
        ),
        migrations.AddField(
            model_name="assessment",
            name="template_version",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assessments",
                to="casework.assessmenttemplateversion",
            ),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(
                fields=["enrollment", "chain_id", "assessment_cycle_number"],
                name="casework_as_enrollm_807fd9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(
                fields=["template_version", "assessment_date"],
                name="casework_as_templat_0d387c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentresponsiblespecialist",
            constraint=models.UniqueConstraint(
                fields=("assessment", "specialist"),
                name="unique_assessment_responsible_specialist",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentresponse",
            constraint=models.UniqueConstraint(
                fields=("assessment", "template_field"),
                name="unique_assessment_template_response",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmenttemplatefield",
            constraint=models.UniqueConstraint(
                fields=("section", "code"), name="unique_assessment_template_field_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmenttemplateversion",
            constraint=models.UniqueConstraint(
                fields=("instrument", "version"),
                name="unique_assessment_instrument_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmenttemplatesection",
            constraint=models.UniqueConstraint(
                fields=("template_version", "code"),
                name="unique_assessment_template_section_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentscoreband",
            constraint=models.UniqueConstraint(
                fields=("template_version", "code"),
                name="unique_assessment_score_band_code",
            ),
        ),
        migrations.RunPython(
            seed_and_migrate_assessments,
            reverse_assessment_migration,
        ),
        migrations.AlterField(
            model_name="assessment",
            name="template_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assessments",
                to="casework.assessmenttemplateversion",
            ),
        ),
    ]
