# Generated by Django 5.2.17 on 2026-08-24 13:04

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

GOAL_CATEGORIES = (
    (
        "CHILD-SAFETY-HYGIENE",
        "Child safety and hygiene",
        "ბავშვის უსაფრთხოება და ჰიგიენა",
        10,
        False,
    ),
    (
        "INDIVIDUAL-DEVELOPMENT",
        "Individual development",
        "ინდივიდუალური განვითარება",
        20,
        False,
    ),
    (
        "DAILY-ACTIVITIES",
        "Daily activities",
        "ყოველდღიური აქტივობები",
        30,
        False,
    ),
    (
        "POSITIVE-PARENTING",
        "Positive parenting",
        "პოზიტიური მშობლობა",
        40,
        False,
    ),
    (
        "KINDERGARTEN-SCHOOL-TRANSITION",
        "Kindergarten or school transition",
        "საბავშვო ბაღში ან სკოლაში გადასვლა",
        50,
        False,
    ),
    (
        "LEGACY-UNCLASSIFIED",
        "Unclassified legacy goal",
        "არაკლასიფიცირებული ძველი მიზანი",
        999,
        True,
    ),
)


def seed_and_migrate_service_plans(apps, schema_editor):
    GoalCategory = apps.get_model("casework", "GoalCategory")
    GoalStatusTransition = apps.get_model("casework", "GoalStatusTransition")
    IndividualPlan = apps.get_model("casework", "IndividualPlan")
    IndividualPlanGoal = apps.get_model("casework", "IndividualPlanGoal")
    ServiceDefinition = apps.get_model("casework", "ServiceDefinition")

    categories = {}
    for code, name_en, name_ka, reporting_order, is_legacy in GOAL_CATEGORIES:
        category, _ = GoalCategory.objects.get_or_create(
            code=code,
            defaults={
                "name_en": name_en,
                "name_ka": name_ka,
                "reporting_order": reporting_order,
                "is_legacy": is_legacy,
                "source_version": "SSK-PLAN-OUTCOMES-1",
            },
        )
        categories[code] = category

    early_intervention_services = ServiceDefinition.objects.filter(
        family="early_intervention"
    )
    for code, *_unused in GOAL_CATEGORIES:
        if code != "LEGACY-UNCLASSIFIED":
            categories[code].applicable_services.add(*early_intervention_services)

    enrollment_ids = IndividualPlan.objects.values_list("enrollment_id", flat=True).distinct()
    for enrollment_id in enrollment_ids.iterator():
        previous_plan = None
        plans = list(
            IndividualPlan.objects.filter(enrollment_id=enrollment_id).order_by(
                "plan_start_date", "created_at", "pk"
            )
        )
        for version_number, plan in enumerate(plans, start=1):
            IndividualPlan.objects.filter(pk=plan.pk).update(
                version_number=version_number,
                previous_plan_id=previous_plan.pk if previous_plan else None,
            )
            previous_plan = plan
        active_plans = [plan for plan in plans if plan.status == "active"]
        if len(active_plans) > 1:
            IndividualPlan.objects.filter(
                pk__in=[plan.pk for plan in active_plans[:-1]]
            ).update(status="superseded")

    legacy_category = categories["LEGACY-UNCLASSIFIED"]
    goals = IndividualPlanGoal.objects.select_related("plan").order_by("created_at", "pk")
    for goal in goals.iterator():
        IndividualPlanGoal.objects.filter(pk=goal.pk).update(
            category_id=legacy_category.pk,
            responsible_specialist_id=goal.plan.specialist_id,
            requires_review=True,
        )
        GoalStatusTransition.objects.create(
            goal_id=goal.pk,
            from_status="",
            to_status=goal.status,
            transition_date=goal.created_at.date(),
            reason="Preserved status recorded during service-plan migration.",
            evidence=goal.progress_notes,
        )


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("casework", "0009_versioned_assessment_engine"),
        ("centers", "0003_staff_contract_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoalCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=48, unique=True)),
                ("name_en", models.CharField(max_length=180)),
                ("name_ka", models.CharField(max_length=180)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("source_version", models.CharField(blank=True, max_length=120)),
                ("reporting_order", models.PositiveIntegerField(default=0)),
                ("is_legacy", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["reporting_order", "name_en", "code"],
            },
        ),
        migrations.CreateModel(
            name="GoalOutcomeMeasurement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("measurement_date", models.DateField(db_index=True)),
                (
                    "numeric_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("rating", models.CharField(blank=True, max_length=120)),
                ("unit_or_scale", models.CharField(blank=True, max_length=120)),
                ("interpretation", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-measurement_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GoalStatusTransition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("achieved", "Achieved"),
                            ("deferred", "Deferred"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("achieved", "Achieved"),
                            ("deferred", "Deferred"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "transition_date",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("evidence", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["transition_date", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="IndividualPlanReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("review_date", models.DateField(db_index=True)),
                (
                    "condition_outcome",
                    models.CharField(
                        choices=[
                            ("improved", "Improved"),
                            ("worsened", "Worsened"),
                            ("stable", "Stable"),
                            ("not_yet_assessed", "Not yet assessed"),
                        ],
                        max_length=24,
                    ),
                ),
                ("rationale", models.TextField()),
            ],
            options={
                "ordering": ["-review_date", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="individualplan",
            name="previous_plan",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="next_plan",
                to="casework.individualplan",
            ),
        ),
        migrations.AddField(
            model_name="individualplan",
            name="review_due_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="individualplan",
            name="version_number",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="individualplangoal",
            name="achieved_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="individualplangoal",
            name="assessment_findings",
            field=models.ManyToManyField(
                blank=True,
                help_text="Assessment records whose findings support this goal.",
                related_name="linked_plan_goals",
                to="casework.assessment",
            ),
        ),
        migrations.AddField(
            model_name="individualplangoal",
            name="baseline",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="individualplangoal",
            name="evidence",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="individualplangoal",
            name="measurable_target",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="individualplangoal",
            name="measurement_type",
            field=models.CharField(
                choices=[
                    ("narrative", "Narrative"),
                    ("numeric", "Numeric"),
                    ("rating_scale", "Rating scale"),
                ],
                default="narrative",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="individualplangoal",
            name="measurement_unit_or_scale",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="individualplangoal",
            name="requires_review",
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
        migrations.AddField(
            model_name="individualplangoal",
            name="responsible_specialist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="responsible_plan_goals",
                to="centers.specialistprofile",
            ),
        ),
        migrations.AddField(
            model_name="servicevisit",
            name="goals_worked_on",
            field=models.ManyToManyField(
                blank=True,
                help_text="Optional goals addressed during this visit.",
                related_name="service_visits",
                to="casework.individualplangoal",
            ),
        ),
        migrations.AlterField(
            model_name="individualplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("superseded", "Superseded"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="draft",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="individualplangoal",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("in_progress", "In Progress"),
                    ("achieved", "Achieved"),
                    ("deferred", "Deferred"),
                    ("cancelled", "Cancelled"),
                ],
                default="planned",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="goalcategory",
            name="applicable_services",
            field=models.ManyToManyField(
                blank=True,
                help_text="Leave empty to allow this category for every service.",
                related_name="goal_categories",
                to="casework.servicedefinition",
            ),
        ),
        migrations.AddField(
            model_name="individualplangoal",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="goals",
                to="casework.goalcategory",
            ),
        ),
        migrations.AddField(
            model_name="goaloutcomemeasurement",
            name="goal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="measurements",
                to="casework.individualplangoal",
            ),
        ),
        migrations.AddField(
            model_name="goaloutcomemeasurement",
            name="recorded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="goal_outcome_measurements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="goaloutcomemeasurement",
            name="source_assessment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="goal_outcome_measurements",
                to="casework.assessment",
            ),
        ),
        migrations.AddField(
            model_name="goalstatustransition",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="goal_status_transitions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="goalstatustransition",
            name="goal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="casework.individualplangoal",
            ),
        ),
        migrations.AddField(
            model_name="individualplanreview",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="casework.individualplan",
            ),
        ),
        migrations.AddField(
            model_name="individualplanreview",
            name="recorded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="individual_plan_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="individualplanreview",
            name="source_assessment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="plan_reviews",
                to="casework.assessment",
            ),
        ),
        migrations.AddIndex(
            model_name="goaloutcomemeasurement",
            index=models.Index(
                fields=["goal", "measurement_date"],
                name="casework_go_goal_id_32774c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="goalstatustransition",
            index=models.Index(
                fields=["goal", "transition_date"],
                name="casework_go_goal_id_f8ee33_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="individualplanreview",
            index=models.Index(
                fields=["plan", "review_date"], name="casework_in_plan_id_ef178c_idx"
            ),
        ),
        migrations.RunPython(
            seed_and_migrate_service_plans,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="individualplangoal",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="goals",
                to="casework.goalcategory",
            ),
        ),
        migrations.AlterField(
            model_name="individualplangoal",
            name="responsible_specialist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="responsible_plan_goals",
                to="centers.specialistprofile",
            ),
        ),
        migrations.AddConstraint(
            model_name="individualplan",
            constraint=models.UniqueConstraint(
                fields=("enrollment", "version_number"),
                name="unique_plan_version_per_enrollment",
            ),
        ),
        migrations.AddConstraint(
            model_name="individualplan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("enrollment",),
                name="one_active_plan_per_enrollment",
            ),
        ),
    ]
